### ISSUE TITLE
Some preview models cut out if they go too far back

### ISSUE THREAD

**Issue by 1unar-Eclipse** [AsoDesu/IslandUtils#101]
**Describe the bug**
_A clear and concise description of what the bug is._
The cosmetic preview player model can be cut off in some cases, making parts of it look odd.

**To Reproduce**
_Steps to reproduce the behaviour:_
1. Go to any screen where the cosmetic preview appears
2. Drag the player around - upward tends to work best
3. ! Parts of the preview model will be cut off

**Expected behaviour**
_A clear and concise description of what you expected to happen._
The player model would not be cut off.

**Screenshots & Logs**
_If applicable, add screenshots or log snippets to help explain your problem._
Bugged:
![image](https://github.com/AsoDesu/IslandUtils/assets/74077800/45f353c0-2147-4601-bf26-4d887f9ecbfe)
(there should be a second antenna thing)
Normal: 
![image](https://github.com/AsoDesu/IslandUtils/assets/74077800/9ce530b1-2de1-452f-8655-02a37a834570)
Problem without any cosmetics: 
![image](https://github.com/AsoDesu/IslandUtils/assets/74077800/ec261cfc-2741-47dc-98e4-6f36f4ae75b2)

**System & Version Information**
_(This can usually be found in the F3 Menu)_
 - Java Version: Java 17.0.8
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.6.1
- OS: Windows 10
- CPU: Ryzen 5 3600

**Additional context**
_Add any other context about the problem here._
This is most obvious if using very big cosmetics (such as Flower Umbrella) and/or other cosmetic mods such as Figura, but it can happen with just the base player if dragged enough.

**Comment by AsoDesu** [comment]
This is a problem with how minecraft renders things and there's not much i can do about it
