### ISSUE TITLE
Remove the Silver counter

### ISSUE THREAD

**Issue by 1unar-Eclipse** [AsoDesu/IslandUtils#105]
**Is your feature request related to a problem? Please describe.**
Now that Silver is gone, the counter is pretty worthless (could be easily repurposed for Royal Reputation though)

**Describe the solution you'd like**
Simply removing the counter makes most sense.

**Describe alternatives you've considered**
Hovering over the Confirm button could give what you'll get from the current scavenging.

**Additional context**
The Mastery update removed Silver and made more than just one thing obtainable from scavenging (namely Spirits).

**Comment by AsoDesu** [comment]
I've already fixed the silver counter and made it show the material dust and ticket counters instead
Showing all items you'll get from scavenging over the confirm button could be good for any items other than dust and tickets

https://github.com/AsoDesu/IslandUtils/commit/e4b327312d87e7e3f0c8b39fc9f356ec92b839d2

**Comment by AsoDesu** [comment]
Fixed in 1.6.2
