### ISSUE TITLE
Island Utils 1.6.2 Incompatible with 1.20.1

### ISSUE THREAD

**Issue by Cycrum** [AsoDesu/IslandUtils#107]
The Island Utils mod, when in 1.6.1 and on 1.20.1, recommends I update it to 1.6.2, which is supposedly available for 1.20.2 and 1.20.1, but the 1.6.2 update is incompatible with 1.20.1, as it requires the most recent version of Noxesium, 1.0.5, which is only compatible with Minecraft version 1.20.2.

**Comment by Cycrum** [comment]
https://media.essential.gg/8efd83a2-b7ce-469c-3c95-8a2f82575a00

**Comment by AsoDesu** [comment]
The one linked by the updater is the 1.20.2 build, are you downloading the build for 1.20.1? (https://modrinth.com/mod/island-utils/version/nKoBFdbG)
