### ISSUE TITLE
Character Preview for Variant Blueprints

### ISSUE THREAD

**Issue by RuiNtD** [AsoDesu/IslandUtils#11]
You can right-click a Variant Blueprint (in both the Infinibag and Crafting Station) to preview it in the menu, but it doesn't show up in the preview.
![](https://i.imgur.com/6w0f1Wd.png)

**Comment by LukynkaCZE** [comment]
Hmm I think Aso was unaware of this feature (the right clicking to preview) when adding the character preview. Will be fixed in next release

**Comment by AsoDesu** [comment]
I am aware of this feature, the reason this wasn't added is because there is no distinct marker as to if it is a hat or accessory, as it's type is "Material".
I'll look into a way to solve this

**Comment by AsoDesu** [comment]
I'm going to close this issue as, as of right now there's no way to detect the type of a variant blueprint,
If this ever changes in the future, I'll reopen this issue

Thank you :D
