### ISSUE TITLE
Texture not found for finished crafts

### ISSUE THREAD

**Issue by TheFox580** [AsoDesu/IslandUtils#111]
**Describe the bug**
The texture to show when craft have finished is not found / available

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the mod
2. Go to your server list / look at MCCI
3. If you have any completed crafts, shows a missing texture
4. If not, make a craft, wait for it to be over, leave the server and repeat step 2

**Expected behaviour**
See the right icon to show

**Screenshots & Logs**
![image](https://github.com/AsoDesu/IslandUtils/assets/44817153/dbe63d04-5a1d-4be0-a63b-7b99d2949cac)

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: Java 17.0.7
- Minecraft Version: 1.20.2
- IslandUtils Version: 1.6.3
- OS: Windows 11
- CPU: Intel i5-8400

**Additional context**
It might be just be me, in that case, i'll have to find out how to fix it

**Comment by AsoDesu** [comment]
MC 1.20.2 is no longer supported on MCC Island
Therefor 1.20.2 will no longer receive support updates, and this bug is already fixed on 1.20.1 & 1.20.4
