### ISSUE TITLE
Add a toggle for the Chat Tabs 

### ISSUE THREAD

**Issue by derNiklaas** [AsoDesu/IslandUtils#112]
**Is your feature request related to a problem? Please describe.**
I prefer having my chat directly above the input line. 

**Describe the solution you'd like**
Add a toggle in the settings that enables/disables the chat buttons 

**Additional context**
I am talking about this: 
![image](https://github.com/AsoDesu/IslandUtils/assets/12937331/27661281-14a5-4470-a7f7-e87daf0a43f2)

**Comment by AsoDesu** [comment]
Added in 1.6.4
