### ISSUE TITLE
Display Faction Mascot instead of MCCI Logo in the discord presence

### ISSUE THREAD

**Issue by LukynkaCZE** [AsoDesu/IslandUtils#114]
The discord presence is already displaying your faction level, it would be nice if it displayed the mascot/icon as well instead of the MCCI logo

![image](https://github.com/AsoDesu/IslandUtils/assets/48604271/4d3b1fd8-1cd7-4bdc-a723-7eb96e88ecd8)

**Comment by AsoDesu** [comment]
i think i tried this at some point while making discord presence but decided against it because i didn't like how it looked
tho i do like having the mcci logo on there

**Comment by AsoDesu** [comment]
![image](https://github.com/AsoDesu/IslandUtils/assets/53526710/2eab65f7-61fb-4c6a-b168-b25cb28363fc)
yea i really don't think they work with the circle cut-out + non-circular faction icon

**Comment by LukynkaCZE** [comment]
Oh yeah I didn't really think of that
