### ISSUE TITLE
Parkour Warrior Dojo splits don't work on 1.20.4

### ISSUE THREAD

**Issue by osfanbuff63** [AsoDesu/IslandUtils#115]
**Describe the bug**
Parkour Warrior Dojo splits do not work on 1.20.4.

**To Reproduce**
1. Go to a Parkour Warrior Dojo instance
2. Make sure that Parkour Warrior Dojo Splits is turned on
3. Finish any obstacle and notice that splits are not activated.

**Expected behaviour**
Splits should have triggered when you join a Parkour Warrior Dojo instance and complete an obstacle.

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: 17
- Minecraft Version: 1.20.4
- IslandUtils Version: 1.6.4
- OS: Windows 11
- CPU: Intel i5-12400

**Additional context**
This is particularly an issue as MCCI removed 1.20.2 support out of nowhere (it worked last night and now doesn't), which is the next stable version down from 1.20.4.

**Comment by AsoDesu** [comment]
I've been able to replicate it, i've also noticed that Discord Presence, Music and basically everything that requires a game currently doesn't work.
This _appears_ to be an issue with IslandUtils not receiving game updates, i'll do a little more debugging now

**Comment by AsoDesu** [comment]
Upon debugging i found that i'm not reciving game updates from MCCI at all on 1.20.4 
I've created a bug report and passed off all my info to them so i'll wait and see if there's anything else i need to do

**Comment by AsoDesu** [comment]
MCCI and Noxesium seem to have fixed the issues with missing packets, this should work now!
