### ISSUE TITLE
Music does not work for me

### ISSUE THREAD

**Issue by UltraTeal** [AsoDesu/IslandUtils#117]
i upgraded versions from 1.20.1 to 1.20.4 and  just updated all my mods and the music isn't working 

![image](https://github.com/AsoDesu/IslandUtils/assets/135456234/158a53e4-4571-4795-a09b-535dca24c873)

**Comment by AsoDesu** [comment]
same issue ass in #115 
it's an MCC Island bug and i've reported it to them.
