### ISSUE TITLE
island utils playing wrong game music

### ISSUE THREAD

**Issue by TheDirtyRowlet** [AsoDesu/IslandUtils#118]
**Describe the bug**
Island utils plays the wrong music or no music in games, such as BB music in SKB in the clip below

**To Reproduce**
Steps to reproduce the behaviour:
Only thing I have is remote queuing SKB from BB, but idk if it is related

**Expected behaviour**
I expected SKB music in SKB but got BB (still was a banger)
**Screenshots & Logs**
If applicable, add screenshots or log snippets to help explain your problem.
https://medal.tv/games/minecraft/clips/22B3MGVXUiqbQp/d1337BxJGpO7?invite=cr-MSxkY2ssMjAwNDU1NTYyLA
**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: 1.7.0.8
- Minecraft Version: 1.20.4
- IslandUtils Version: 1.6.4 (1.20.4)
- OS: Windows
- CPU: 18x AMD Ryzen 7 5700 G with Radeon Graphics

**Additional context**
Music playing can be inconsistent at times, sometimes does not play at all when enabled

**Comment by AsoDesu** [comment]
this is caused by the same issue as in #115
