### ISSUE TITLE
Quest recap while entering games

### ISSUE THREAD

**Issue by wolfplay013** [AsoDesu/IslandUtils#122]
**Is your feature request related to a problem? Please describe.**
I sometimes misremember quests or forget that there are quests and what kind, and even then if I remember, there is a chance that I don't check the quest book to see which quests are possible

**Describe the solution you'd like**
Have a recap of all of the quests in the chat right after the tutorial begins.
I'd imagine for example when you join PKWS, you'd see these messages pop up when you join.
`(■) Available Quests`
`- Outlive 10 players in Parkour Warrior Survivor. (0/10)`
`- Complete Leap 4 in 2 games of Parkour Warrior Survivor (1/2)`
(■ being the quest log icon)

**Describe alternatives you've considered**
These will be very likely more complex and maybe even worse but you could have the quests in the bossbar.

**Comment by AsoDesu** [comment]
hey! there is a lot i've wanted to do relating to quests, however the main issue is that there is no way for me to get your current quests without you opening the quest book, and saving them.
even then, if your quests change (from a quest refresher or daily reset) you'd need to open the book again to save the new ones.

maybe one day if the mcci api gives access to quests, but right now this isn't something that can be done
