### ISSUE TITLE
Rocket Spleef Rush music does not play

### ISSUE THREAD

**Issue by gassug3** [AsoDesu/IslandUtils#124]
Rocket Spleef Rush music does not play when expected. Setting is enabled via ModMenu and game music volume is set to 60%.

Steps to reproduce the behaviour:
1. Enter a game of Rocket Spleef Rush
2. Verify that game music volume is audible and Rocket Spleef Rush music is enabled
3. Play the game, and notice the absence of music.

**Expected behaviour**
Expected Rocket Spleef Rush music to play after the pre-game countdown ended.

**System & Version Information**
 - Java Version: OpenJDK JRE 17
- Minecraft Version: 1.20.4
- IslandUtils Version: 1.6.5
- OS: Arch Linux (amd64)
- CPU: AMD Ryzen 7 5800X3D

**Additional context**
In-game music works in Parkour Warrior, unlikely to be an issue with sound altogether. Using PipeWire sound server (as a PulseAudio replacement).

**Comment by AsoDesu** [comment]
Fixed in 1.6.6
