### ISSUE TITLE
Completed Crafts doesn't update for old items

### ISSUE THREAD

**Issue by TheFox580** [AsoDesu/IslandUtils#126]
**Describe the bug**
As Binding Gels are inexistant now, it doesn't get updated in the notification system

**To Reproduce**
(Can't anymore as Binding Gels have been removed from the server)

**Expected behaviour**
As it has been claimed, the item should be removed from the notification

**Screenshots & Logs**
![Binding Gel notification not updating](https://github.com/AsoDesu/IslandUtils/assets/44817153/f79ab6d8-aead-4d43-b3cb-87b797521ac7)
![No Binding Gel in the forge](https://github.com/AsoDesu/IslandUtils/assets/44817153/7c012647-89ed-4cfe-82d7-00f9d0809ddc)

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: Java 17.0.8
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.6.6
- OS: Windows 11
- CPU: Intel I5-8400

**Additional context**
It's completely understandable if this doesn't get updated, i don't mind it.

**Comment by AsoDesu** [comment]
I've replicated this issue previously, the exact issue is that the crafting menu's slots have moved, and the system uses the slot number to identify each craft.
since those slots are no longer used, they're never identified as empty and thus stay in the system.

**Comment by AsoDesu** [comment]
Fixed with https://github.com/AsoDesu/IslandUtils/commit/8b30a9f1336beb38e90cb634fb7de7d5007139b6
