### ISSUE TITLE
Cosmetic preview paper doll doesn't render properly when Noxcrew/SheepLib is also installed

### ISSUE THREAD

**Issue by lucyydotp** [AsoDesu/IslandUtils#127]
Hey! Just thought I'd let you know that I'm looking into a bug that I think a few mods have reported privately, where the paper doll is clipped out of view when [SheepLib](/Noxcrew/SheepLib) is installed.

I'm still yet to figure out the exact repro steps, it only happens sometimes depending on what other mods are installed. I'll comment here once I figure it out.

This is probably an issue on my end - SheepLib does some quite invasive Z-index shenanigans to get its dialogs to render properly.

![image](https://github.com/AsoDesu/IslandUtils/assets/35287819/51c43370-5e35-4777-845a-50897b424468)

**Comment by lucyydotp** [comment]
You're welcome to assign this issue to me btw. I'm happy to PR a fix here if the need arises seeing as I've broken this :P

**Comment by AsoDesu** [comment]
i'll assign this to you then,
thanks for the help! :D
