### ISSUE TITLE
game instantly crashes after joining mcci

### ISSUE THREAD

**Issue by ghostieslive** [AsoDesu/IslandUtils#128]
**Describe the bug**
game instantly crashes after joining mcci

**To Reproduce**
Steps to reproduce the behaviour:
1. Open 'Minecraft'
2. Click on 'Multiplayer'
1. Go to 'mccisland.net'

**Expected behaviour**
not crash

**Screenshots & Logs**
https://mclo.gs/xVyEM5c

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: Java 17
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.6.6
- OS: Windows 10 Pro
- CPU: Intel i5-12600K

**Additional context**
no

**Comment by pe3ep** [comment]
Axiom seems to cause this issue to accur

**Comment by AsoDesu** [comment]
yea, i have a fix for the axiom conflict on 1.20.4 but i need to commit it to 1.20.1 as well

**Comment by AsoDesu** [comment]
Could you try using this version of the mod and let me know if it's fixed?
https://github.com/AsoDesu/IslandUtils/actions/runs/8766732810/artifacts/1432214919

**Comment by ghostieslive** [comment]
> Could you try using this version of the mod and let me know if it's fixed? https://github.com/AsoDesu/IslandUtils/actions/runs/8766732810/artifacts/1432214919

it's fixed now!!! 😁

**Comment by AsoDesu** [comment]
ty! :D
