### ISSUE TITLE
Opening a chest in Sky Battle causes Accessory to overwrite offhand

### ISSUE THREAD

**Issue by Sorbetess** [AsoDesu/IslandUtils#13]
When I right-click with the item, it seems to revert back to normal, but opening a chest causes the issue again.

I believe this also happens even when the Model Preview is turned off, so I'm not quite sure what's happening here.

[A video replicating the issue can be found here.](https://imgur.com/a/UGPpx41)

**Comment by ByrtZ** [comment]
I encountered this happening when opening any kind of UI across the entire server (Inventory, chests, custom UIs, etc.)

**Comment by LukynkaCZE** [comment]
Fixed this in [hotfix release 1.1.1](https://github.com/AsoDesu/IslandUtils/releases/tag/1.1.1)
