### ISSUE TITLE
Weird behavior with mod using Lunar Client

### ISSUE THREAD

**Issue by kispintyi** [AsoDesu/IslandUtils#130]
**Describe the bug**
When using the mod with Lunar Client (custom mod feature like Feather Client) the mod behaves strangely in some areas. I've waited a lot of time now and Lunar has improved this feature since then but there is no change on Island Utils' side so I'm reporting it now.
_The Features that are broken:_
- **Music**
- **Message to show friends in the same game/lobby**

_How are they broken:_
**1. Music:**
Most of the time the Music doesn't start at all, if it does start it will play until you leave that game server/game arena. It looks like it happens randomly.

**2. Friend messages:**
It spams the chat randomly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have Island Utils installed to `C:\Users\pcusernamehere\.lunarclient\offline\multiver\mods\fabric-1.20.4`
3. Start Lunar Client 1.20.4
4. Log on to MCC Island and have a friend in the same lobby/game server as you
5. See error (Messages duplicating)

**Expected behaviour**
Music starts in every game I have it enabled in the settings and ends when the overtime music starts playing.
Friend messages are sent once.

**Screenshots & Logs**
Example for the friend messages spamming the chat (I use a duplicate message stacker feature):
![2024-04-20_17 55 07](https://github.com/AsoDesu/IslandUtils/assets/116653691/913f075d-844f-433a-a728-5de064438d41)
Logs:
Main Lunar Client Log (file location: `C:\Users\pcusernamehere\.lunarclient\logs\`): [main.log](https://github.com/AsoDesu/IslandUtils/files/15048918/main.log)
Lunar Client Game Log (file location: `C:\Users\pcusernamehere\.lunarclient\logs\game`): [9b8ce8d2-61a4-44a5-ba54-4dee02e8cad1-master.log](https://github.com/AsoDesu/IslandUtils/files/15048919/9b8ce8d2-61a4-44a5-ba54-4dee02e8cad1-master.log)
**Note: LunarClient doesn't log into the .minecraft folder!**

**System & Version Information**
 - Java Version: Java 17.0.3
- Minecraft Version: Lunar Client 1.20.4 (v2.15.1-2416)
- IslandUtils Version: Hotfix 1.6.6 - 1.20.4
- OS: Windows 11
- CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

**Additional context**
Lunar Client's custom mod support was bad months before but now almost every mod works with it however Island Utils still doesn't function 100% correctly.
The mod works 100% correctly with Feather Client.

**Comment by kispintyi** [comment]
# UPDATE:
**Notice from Lunar:** Mod compatibility is still a work in progress.

**Comment by AsoDesu** [comment]
I'm unable to replicate with just IslandUtils, Yacl and Noxesium on Lunar 1.20.4,
Could you lmk if you have any other mods installed?

Also could you use this version of the mod, replicate the issue and send me another log file, this should give me more information that could hopefully diagnose the issue?
https://github.com/AsoDesu/IslandUtils/actions/runs/8766709294/artifacts/1432209799

**Comment by kispintyi** [comment]
Mods:
- borderless mining 1.1.9 - 1.20.2
- cloth config 13.0.121
- cullclouds 0.1.0
- cullleaves 3.3.0
- eating animation 1.9.61 - 1.20
- enhanced attack indicator 1.0.4 1.20.3
- enhanced block entities 0.9.1 - 1.20.2
- entityculling 1.6.4 - 1.20.4
- exordium - 1.2.1 - 1.20.4
- fabric API 0.92.0 - 1.20.4
- force close loading screen 2.2.1
- held item info 1.5.0
- indium 1.0.30 - 1.20.4
- islandutils 1.6.7 (pre-pre 172 main) - The mod you sent me
- krypton 0.2.6
- lithium 0.12.1 - 1.20.4
- mcci nametag mod 1.9.1
- memoryleakfix 1.17; 1.1.5
- mixintrace - 1.1.1; 1.17
- modelfix 1.14
- modmenu 9.1.0 beta 1.
- more culling 1.20.4 0.22.1
- more culling extra 1.1 - 1.20.1
- notenoughcrashes 4.4.7 - 1.20.4
- noxesium 1.2.0
- nvidium 0.2.6 beta
- reeses sodium options 1.7.2 - 1.20.4
- sodium extra 0.5.4; build 116 - 1.20.4 
- spark 1.10.61
- starlight 1.1.3; f5dcd1a
- very many players 0.2.0 beta 7.139-all - 1.20.4
- yet another config lib 3.3.1 - 1.20.4
Lunar Client built-in fabric module mods:
- Sodium 0.5.8
- Iris 1.6.17
- Lithium 0.12.1
- Indium 1.0.30
- FerriteCore 6.0.1
- Noxesium 1.2.0

I tested the mod you sent me, but it still doesn't work even if it's enabled in the Island Utils settings (Music)
Here are the log files:
- [a707efec-9883-4f87-86cb-cfcbcdd960e8-master.log](https://github.com/AsoDesu/IslandUtils/files/15049281/a707efec-9883-4f87-86cb-cfcbcdd960e8-master.log)
- [main.log](https://github.com/AsoDesu/IslandUtils/files/15049282/main.log)

**Comment by kispintyi** [comment]
I tested it with only the Lunar added mods
+ Noxesium, yet another config lib and IslandUtils and it doesn't work
Logs:
- [main.log](https://github.com/AsoDesu/IslandUtils/files/15049350/main.log)
- [02724341-c76a-49a2-a4b8-d028255d00c0-master.log](https://github.com/AsoDesu/IslandUtils/files/15049354/02724341-c76a-49a2-a4b8-d028255d00c0-master.log)

I tested it with the Modrinth app and it works perfectly fine!

**Comment by AsoDesu** [comment]
yea i'm not able to replicate this at all

**Comment by kispintyi** [comment]
can you add me on Discord please?
Discord name: kispintyi

**Comment by kispintyi** [comment]
# UPDATE:
I think it's related to this issue that it doesn't release an old config file or something because I added your mod when the custom mods feature first came out: https://github.com/AsoDesu/IslandUtils/issues/126

**Comment by kispintyi** [comment]
I tested it with my friend and it only happens for me.

**Comment by kispintyi** [comment]
# UPDATE - FIXED
If anyone experiences this issue just reset Island Utils' settings and the problem is solved!

**Comment by kispintyi** [comment]
![image](https://github.com/AsoDesu/IslandUtils/assets/116653691/841a7a7f-4ed9-456f-9226-25ae3b382a8a)

**Comment by kispintyi** [comment]
@AsoDesu the problem is solved! It was an old config issue!

**Comment by kispintyi** [comment]
Unfortunately I just got lucky and this isn't the solution for this, it's still happening

**Comment by kispintyi** [comment]
## After a lot of frustration, I finally figured it out:

# - DISABLE PING MOD IN LUNAR!!!! It's causing the issue!
![image](https://github.com/AsoDesu/IslandUtils/assets/116653691/a638c56a-709d-41af-9958-bb79629fdc92)
