### ISSUE TITLE
IslandUtils breaks in games with Lunar Client's Ping mod enabled

### ISSUE THREAD

**Issue by BluSpring** [AsoDesu/IslandUtils#131]
**Describe the bug**
When playing any MCCI games, many of IslandUtils' in-game features will end up failing to trigger, caused by Lunar Client's Ping mod.
This includes:
- Game music failing to start
  - This occurs at random, where sometimes it will play, and sometimes it won't.
  - In Parkour Warrior Dojo's case however, when it does randomly play, if you restart the course the music does not stop.
- Parkour Warrior splits stop functioning
- Friends in chat fail to display

**To Reproduce**
- Install Lunar Client
- Enable the Ping mod
- Enable the "Show Ping Nametag" option in the Ping mod

**Expected behaviour**
Everything is fine, all is good.

**Screenshots & Logs**
![image](https://github.com/AsoDesu/IslandUtils/assets/20620191/ff985925-3bdf-4534-a749-3d1a1f7f5b45)
[67f536c8-d137-4c4e-b7f4-ae617538994f-master.log](https://github.com/AsoDesu/IslandUtils/files/15051293/67f536c8-d137-4c4e-b7f4-ae617538994f-master.log)

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: Azul Zulu 17.34.19 JDK 17.0.3
- Minecraft Version: 1.20.4
- IslandUtils Version: 1.6.6
- OS: Windows 11
- CPU: AMD Ryzen 7 7700X

**Additional context**
..

**Comment by AsoDesu** [comment]
Can confirm, i have been able to reproduce👍

**Comment by AsoDesu** [comment]
Fixed with https://github.com/AsoDesu/IslandUtils/commit/07f6e3eb6319cfcaa346a076e816657c3c97bdae
