### ISSUE TITLE
Game music not playing

### ISSUE THREAD

**Issue by radstevee** [AsoDesu/IslandUtils#133]
**Describe the bug**
The in-game music is not playing.

**To Reproduce**
Steps to reproduce the behaviour:
- Use 1.20.4
- Use noxesium 1.2.1
- Use IslandUtils 1.6.8

**Expected behaviour**
The music should be playing once I enter a game.

**Screenshots & Logs**
![image](https://github.com/AsoDesu/IslandUtils/assets/96977790/6d75d554-d57b-45be-9ffb-c4af3497585e)
![image](https://github.com/AsoDesu/IslandUtils/assets/96977790/df49e156-885b-4efc-b946-bf92b46996ff)

**System & Version Information**
(This can usually be found in the F3 Menu)
- Java Version: 17.0.9
- Minecraft Version: 1.20.4
- IslandUtils Version: 1.6.8
- OS: Archlinux
- CPU: AMD Ryzen 3 4300G

**Additional context**
-

**Comment by AsoDesu** [comment]
Please send your latest log file from when this issue occurred.

**Comment by radstevee** [comment]
@AsoDesu http://0x0.st/XH4R.log

**Comment by anastarawneh** [comment]
I'm 90% sure this is a Noxesium issue, the server packets aren't being received. I have another mod that depends on them that isn't receiving game state and server packets.

**Comment by AsoDesu** [comment]
a new version of noxesium was just released which have fixed this, please try, and lmk if that fixes the issue
https://modrinth.com/mod/noxesium/version/1.2.2

**Comment by anastarawneh** [comment]
Doesn't appear to be resolved (Noxesium 1.2.2, IslandUtils 1.6.8).

**Comment by AsoDesu** [comment]
could you send me another log from after the update, there could be something else that's causing it then

**Comment by anastarawneh** [comment]
https://hst.sh/uyuwowikuj
Still looks a Noxesium issue to me.

**Comment by radstevee** [comment]
Can confirm, has not been resolved.

**Comment by AsoDesu** [comment]
I have been able to replicate 👍 
(I realised i was using an older version of noxesium oops..)

**Comment by radstevee** [comment]
![Screenshot_20240429-154508-756.png](https://github.com/AsoDesu/IslandUtils/assets/96977790/5e45988c-13ef-42f3-9ae2-12d883bf46b2)

This is now indeed a confirmed Noxesium issue 👍

**Comment by gassug3** [comment]
Same issue, curiously also using Arch Linux with PipeWire.

**Comment by alexthyst** [comment]
Works for me with Noxesium 1.2.0, will just have to wait until a hotfix is released so that the issue can be fixed

**Comment by radstevee** [comment]
Should be fixed in the latest Island patch. Can anyone confirm?

**Comment by radstevee** [comment]
Fixed :+1:
