### ISSUE TITLE
Update reminder text on the title screen is actually broken

### ISSUE THREAD

**Issue by KaaayKaay** [AsoDesu/IslandUtils#134]
# Version used

Fabric 1.20.1
Hotfix 2.6.8 - 1.20.1

# The bug
Island Utils tells me to update to the latest version when I am on the latest version (I checked), when I click the interactable text, it links me to the 1.20.6 version.

# The feature is just cringe

An easy way to fix this would be to just have the feature a toggle, because for modpack developers this is a nightmare, having to release a new version of your pack just to fix an issue, where your UI looks horrible and is overlayed by a bunch of text, just to realize it was caused by another developer.

# Extra info

This is what the UI looks like on my 20k+ downloaded pack until you fix this lmao

![image](https://github.com/AsoDesu/IslandUtils/assets/137423230/0f458d18-ae8b-4611-8532-c832e76d4e9e)

**Comment by AsoDesu** [comment]
the update checker is something i've been meaning to fix and update for a while now, mostly because of conflicts with other mods and issues with new minecraft versions with the same version number.

tho island utils can have some critical updates for island compatibility (there have been crashes and major feature breaks which have happened before) which is why it is where it is.
but i do agree it doesn't belong on the main menu, at least not positioned where it is.

**Comment by LobbyLC** [comment]
Hey, I'm not sure if you missed this as it was unclear in your response so I just wanted to clarify, I believe what KaaayKaay was referring to was the fact the update checker is saying they're not on the latest version, even though they are.

As of 1.6.8+1.20.6, if you open Minecraft, it will tell you an Island Utils update is available, even though that's the latest version. Apologies if that's just repeating what you already knew, but I couldn't really tell so thought I'd speak up.

**Comment by AsoDesu** [comment]
yep that's what i meant by "issues with new minecraft versions with the same version number"

**Comment by LobbyLC** [comment]
Ah okay, I just wanted to confirm you were aware haha, my apologies.

**Comment by Pyro0TV** [comment]
So there's no current way to disable this on 1.20.4 
![image](https://github.com/AsoDesu/IslandUtils/assets/141536178/f06fcca2-6379-434f-8f6c-582d2fc9c275)
epic 😭
