### ISSUE TITLE
Custom Vignette Effect for RSR

### ISSUE THREAD

**Issue by kispintyi** [AsoDesu/IslandUtils#136]
**Is your feature request related to a problem? Please describe.**
Enhancement

**Describe the solution you'd like**
It would be great to have a transitional Vignette effect for RSR when the Elytra are starting to break like how close you are to the world border in Sky Battle.

**Describe alternatives you've considered**
DamageVignette mod but that isn't related to Elytra durability, so it doesn't work.

**Additional context**
Illustration (when players hit me it turns the screen to a red color): ![image](https://github.com/AsoDesu/IslandUtils/assets/116653691/07560088-1a97-478b-84b0-4e76809a599c)

**Comment by AsoDesu** [comment]
afaik RSR already has a vinette effect when you're close to the death border on the bottom, and also this is *kind of* a change to gameplay, and i don't really want to change gameplay. 
thanks for the suggestion tho! :D
