### ISSUE TITLE
Update Notifier

### ISSUE THREAD

**Issue by Pyro0TV** [AsoDesu/IslandUtils#138]
The Update Notifier keeps saying "New Update: Click to update" or whatever, when I already have that version downloaded. Mod Menu also displays that I have the latest version.

1. Have IslandUtils v1.6.8 (for 1.20.6) + dependencies if has any (Noxesium idk)
2. Boot up minecraft
3. Look at the spot the notifier appears at
4. "why do i need to update to 1.6.8 if I'm already on 1.6.8

- Minecraft Version: 1.20.6
- Mod Version: 1.6.8
- Windows

Notifier telling me to Update
![image](https://github.com/AsoDesu/IslandUtils/assets/141536178/af68d316-970d-47f8-a75a-66b41bbda48c)
Mod Menu saying im on latest
![image](https://github.com/AsoDesu/IslandUtils/assets/141536178/f91e944a-3bd9-4da3-b098-4f5abe610a1e)

then it brings me here when thats the one i got https://modrinth.com/mod/island-utils/version/1.6.8+1.20.6

**Comment by AsoDesu** [comment]
yea this is a known issue with the updater
is also mentioned in #134
