### ISSUE TITLE
Death screen does not have the exit server confirmation

### ISSUE THREAD

**Issue by wolfplay013** [AsoDesu/IslandUtils#141]
**Describe the bug**
The death screen does not have the exit server confirmation when you have Confirm before Disconnect enabled.

**To Reproduce**
1. Die
2. Click on "Title Screen"

**Expected behaviour**
The confirmation would have been there, so you wouldn't have accidentally left the server.

**System & Version Information**
(This can usually be found in the F3 Menu)
- Java Version: Java 17.0.5 64-bit
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.6.8
- OS: Windows
- CPU: AMD Ryzen 5 2600

**Comment by AsoDesu** [comment]
minecraft already has a confirmation screen when you click "Title Screen" in the death menu

**Comment by wolfplay013** [comment]
for some reason it doesn't work for me then, every time i accidentally press on Title Screen. it immediately boots me out without any confirmation.
