### ISSUE TITLE
Mod claiming an update is available when there is no update

### ISSUE THREAD

**Issue by 1unar-Eclipse** [AsoDesu/IslandUtils#143]
**Describe the bug**
Some parts of Island Utils claim that there is a newer update than what's currently installed. However, these do not exist.

(Mod version 1.6.8, Minecraft version 1.20.6)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game
2. ! Main menu claims there is an Island Utils update
3. Join MCC Island
4. ! Chat claims there is an Island Utils update
5. Both links direct to the same mod version I am currently using

**Expected behaviour**
There would not be redundant update messages.

**Screenshots & Logs**
If applicable, add screenshots or log snippets to help explain your problem.
![image](https://github.com/user-attachments/assets/f2f89b4a-e9d8-4c42-bc35-45da9b3af48e)
![image](https://github.com/user-attachments/assets/5c30a7e1-488f-405b-846d-8d20b14758fb)

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: 21.0.3
- Minecraft Version: 1.20.6
- IslandUtils Version: 1.6.8
- OS: Windows 10
- CPU: Ryzen 5 3600

**Additional context**
Mod Menu's update checker doesn't make the same claims as Island Utils itself.
![image](https://github.com/user-attachments/assets/e4e43979-5ff4-4616-99f8-9152d012d176)

**Comment by LukynkaCZE** [comment]
This is already fixed and will be part of the 1.21 release
