### ISSUE TITLE
Add the Lobby Music from the Bedrock Event

### ISSUE THREAD

**Issue by mario-gaming** [AsoDesu/IslandUtils#144]
MCC partnered up with Minecraft for a special 14-day event, where they launched a temporary server on Bedrock Edition, with MCC minigames, on that server, there was never-before-heard music for the lobby. I want to request this music be added to IslandUtils, as I believe it fits the general chill vibe of the MCC Island lobby.

Here is the music in question:
https://www.youtube.com/watch?v=Il-WO5FfyLM

Thank you.

**Comment by LukynkaCZE** [comment]
Hi! Thanks for the suggestion however the music has not been officially released and even then, redistributing it would be against copyright laws
