### ISSUE TITLE
Game Crash During Initialization Due to IslandUtils Mod

### ISSUE THREAD

**Issue by SixFlixGG** [AsoDesu/IslandUtils#158]
**Description**  
The game crashes while initializing with an error message related to the "islandutils" mod. The message states:  
*`java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'islandutils' at 'net.asodev.islandutils.IslandUtilsClient'`*

Steps to reproduce the behaviour:
1. Launch the game with the "islandutils" mod installed.
2. Wait for the game to initialize.
3. The game crashes during the loading screen with the error mentioned above.

**Expected behaviour**  
The game should start and load all mods without crashing.

**Screenshots & Logs**  
![imagen_2024-11-01_182521092](https://github.com/user-attachments/assets/dc64dcfd-04e3-47ed-badf-99c6a3ddc647)

**System & Version Information**  
- Java Version: Java 8
- Minecraft Version: 1.21.1
- IslandUtils Version: 1.6.10
- OS: Windows 10
- CPU: Intel i5-1035G1

**Additional context**  
I have tried updating and reinstalling the mod, but the issue persists. There may be a compatibility issue with other mods, but I am unsure. Any guidance would be appreciated.

**Comment by LukynkaCZE** [comment]
Downgrade your noxesium to 2.3.0

**Comment by thehamish555** [comment]
just want to say, this was fixed for a newer version of noxesium, not sure about the latest. #155 

Its just that a new release has not been made since the fix. So you could always try self building
