### ISSUE TITLE
Second hand in the inventory on battle box bugs

### ISSUE THREAD

**Issue by hugge64** [AsoDesu/IslandUtils#16]
When i played Battle box with the IslandUtils i had my crossbow in my second hand, but it bugs and disappears etc. I tried without the IslandUtils and it worked fine. So somethings wrong with the second hand in the inventory on Battle box.

**Comment by LukynkaCZE** [comment]
Known issue already reported in #13 
Will be fixed in next release

**Comment by LukynkaCZE** [comment]
Fixed this in [hotfix release 1.1.1](https://github.com/AsoDesu/IslandUtils/releases/tag/1.1.1)
