### ISSUE TITLE
Character Preview should also update in barber when selecting a color

### ISSUE THREAD

**Issue by FayneAldan** [AsoDesu/IslandUtils#19]
The barber only updates when hovering over a style (at the bottom) or the item on the right. I believe it should also update immediately when selecting a color.

![image](https://user-images.githubusercontent.com/1149870/190334287-e287eecd-2b48-4bf6-bbe4-c5d867e9b552.png)

**Comment by AsoDesu** [comment]
This is a change that has been very requested, and i have a plan,
it will be added next update

**Comment by AsoDesu** [comment]
Added in 1.1.3
