### ISSUE TITLE
Game-Specific Suggestions

### ISSUE THREAD

**Issue by Flameri** [AsoDesu/IslandUtils#2]
Can I just say that this is an amazing mod and can't wait to see how it develops! Here are my suggestions for new features you could implement:

Battle Box:
Add a pop-up when everyone on the enemy team is dead (to remind you to fill).
Add a warning when you're in the radius of one of your own (or the enemy's) timed orbs.

Hole In The Wall:
Add a countdown until the next event (and how long the current event has left).

Sky Battle:
Add a display when the border is getting very close.
Add a display for how far away the border is from the player.
Add a warning when you're in the radius of one of your own (or the enemy's) timed orbs.

Add a pop-up when you get the max score in a game.
Also add auto gl and auto gg if possible.

(I don't know how to add tags I'm sorry)

**Comment by AsoDesu** [comment]
These are all very doable.
I worry some could be considered cheating, but i will see what i can do

**Comment by Flameri** [comment]
I can see how some may be cheating.
Also can you add a way to remove those new Announcement messages in chat? They're really annoying.

**Comment by AsoDesu** [comment]
List:
- [ ] Countdown to the next event (HITW)
- [ ] Auto `gg` and `gl` (Global)
- [ ] Toggle announcements (Global)

I will ask around and see what other people will consider cheating

**Comment by AsoDesu** [comment]
Hi, sorry, i've asked some people and most of them consider almost all of these cheating.
Auto `gg` and `gl` i can't add for various reason 
And i would rather annoucement stay as they may be used to show important information in the future.

Than you.
