### ISSUE TITLE
Suggestion: Angle the character preview up a bit?

### ISSUE THREAD

**Issue by FayneAldan** [AsoDesu/IslandUtils#20]
I believe the character preview should be angled slightly more upwards. Currently, with it facing straight forward, the top part of the headphones becomes invisible, since it has no side texture. Plus, it would allow you to see the tops of some of the hats, like the cardboard box.

EDIT: An alternative would be to allow the user to move the preview up and down themselves, but I feel like it would be better to just have a preset angle.

![image](https://user-images.githubusercontent.com/1149870/190334972-2e4d4bd7-74ff-472d-abbd-860853294e39.png)

**Comment by AsoDesu** [comment]
Added in 1.1.3
