### ISSUE TITLE
music wont stop when ReQing in the midle of the game

### ISSUE THREAD

**Issue by spaceCat2345** [AsoDesu/IslandUtils#21]
/hub also has the same effect

**Comment by AsoDesu** [comment]
What mods are you uisng?

**Comment by spaceCat2345** [comment]
![image](https://user-images.githubusercontent.com/113781132/190918530-448c783e-1f52-49c7-9150-1e1e28f54eff.png)
running on Father client

**Comment by spaceCat2345** [comment]
dose that do anything cause I just thought every one was experiencing the same bug?

**Comment by spaceCat2345** [comment]
if you want me to delete one of the mods I can but the ones that improve my fps are mandatory to keep my game running smoothly otherwise my game would look like a complete slide show. :D

**Comment by AsoDesu** [comment]
i dont get the bug, as the music stops for me once i switch to another transition,
i suspect a mod might keep music going even through server transition

**Comment by spaceCat2345** [comment]
ferritecore might be the problem cuse i don't know what it optimizes

**Comment by AsoDesu** [comment]
Should now be fixed in 1.1.3
Please lmk if it isn't
