### ISSUE TITLE
Game crashes after loading up game using 1.1.3

### ISSUE THREAD

**Issue by TheShazyl** [AsoDesu/IslandUtils#23]
both the game and launcher crash after loading up the game using the newest version of the mod. this could just be a pc issue but I haven't had this issue using previous builds of the mod.

**Comment by AsoDesu** [comment]
Can you send the crash log?
What other mods are you using (if any)?
And what versions of Minecraft, Fabric Loader, and Fabric API are you using?

**Comment by TheShazyl** [comment]
Hey! sorry for the late response, I don't check GitHub much, I have attached the following images to answer the questions above (I'm assuming the first image I send is the crash log), i tried loading up this version of the mod on 1.19.2 fabric and 1.19.1 fabric, both versions that should work according to the post
<img width="429" alt="image" src="https://user-images.githubusercontent.com/114727951/195024172-5bb47712-029f-473c-bb39-3992e4170061.png">

1.19.1 Fabric
<img width="591" alt="image" src="https://user-images.githubusercontent.com/114727951/195024878-55219e78-d6ce-463d-b84a-c1cd4d97420f.png">

1.19.2 Fabric
<img width="535" alt="image" src="https://user-images.githubusercontent.com/114727951/195024544-8d2db975-de77-4e05-b0c9-dfddceadfb07.png">

if I have attached the wrong images etc, please let me know and ill try to get back to you sooner this time!

**Comment by TheShazyl** [comment]
using MCCI Utils 1.1.2 works on both the 1.19.2 and 1.19.1 mods

**Comment by AsoDesu** [comment]
Is this still an issue?

**Comment by TheShazyl** [comment]
Hi again, i haven’t used the mod as of recent, so i’ll have to get back to you roughly around 12 hours from now.

**Comment by TheShazyl** [comment]
hello, i forgot abt this (again), anyways, the crashing no longer occurs

**Comment by AsoDesu** [comment]
yay :D
