### ISSUE TITLE
Offhand accessories preview showing at the wrong place

### ISSUE THREAD

**Issue by LiamDun** [AsoDesu/IslandUtils#24]
This is how cosmetics are currently shown when they're actually equipped, where the offhand accessory isn't on top of the chat indicator
![How it should look like](https://user-images.githubusercontent.com/62409548/193438185-564056f5-3329-4eb3-85c9-5a930a1c0600.png)
This is how accessory previews look like, with the offhand accessory being on top of the chat indicator
![How it actually looks like](https://user-images.githubusercontent.com/62409548/193438198-9a8b7e0e-99e1-4f13-ad21-b9e2d7a0a861.png)

**Comment by AsoDesu** [comment]
i will look into this,
however i suspect this is something that is handled by the Minecraft Server, and so i cannot easily fix it

**Comment by LiamDun** [comment]
Yeah I figured it's something Noxcrew does to move the text when there's something in the offhand so I imagine it wouldn't be easy to fix it client side, just thought I would point it out.

**Comment by AsoDesu** [comment]
I'm probably not going to fix this, it's a lotta work and it doesn't really affect much
