### ISSUE TITLE
TGTTOS, Battle Box Remix (Music)

### ISSUE THREAD

**Issue by kispintyi** [AsoDesu/IslandUtils#29]
It would be great to include these Remixes (if Owner gives permission to do so) with a toggleable switch to turn Remix on or off

The User who created these Remixes [Username: Epic]
 (https://mccisland.net/members/epic.32217/):

 https://mccisland.net/threads/to-get-to-the-other-side-and-battle-box-remix-i-made.2155/

The Remixes:

TGTTOS: https://cdn.discordapp.com/attachments/946496967868035124/1013756851478872105/tgttosawaf.ogg

Battle Box: https://cdn.discordapp.com/attachments/946496967868035124/1013756851977998386/Battle_box.mp3

**Comment by AsoDesu** [comment]
Documentation will be made soon on how to change the IslandUtils music.
For the time being i would like to keep the IslandUtils Music to the MCC music, and maybe add remixes and other music later
