### ISSUE TITLE
Discord Presence creates internal exception

### ISSUE THREAD

**Issue by PhokosMC** [AsoDesu/IslandUtils#32]
Error Occurred as follows:
When loading onto servers, it says:
Fail to connect to the servers
Internal Exception: java.lang.UnsatisfiedLinkError:'long de.jcm.discordgamesdk.activity.Activity.allocate()'
<img width="1552" alt="Screenshot 2022-12-14 at 7 30 17 PM" src="https://user-images.githubusercontent.com/107605846/207583980-62d8e50c-ee14-4764-abf0-c1d4eabc04ac.png">

**Comment by LukynkaCZE** [comment]
This should be fixed now so I will close this issue

**Comment by eklyst** [comment]
i still have this issue

**Comment by eklyst** [comment]
is there any way to have the mod without the discord presence feature entirely

**Comment by Architect1st** [comment]
I'm also having this issue. :/

**Comment by AsoDesu** [comment]
Could any of you please send me a log?
Also if you're having this issue, you might be able to disable discord presence and not have this, but i'm not too sure.

**Comment by ColaniYT** [comment]
> Could any of you please send me a log? Also if you're having this issue, you might be able to disable discord presence and not have this, but i'm not too sure.

[latest.log](https://github.com/AsoDesu/IslandUtils/files/11011002/latest.log)

also have the issue, here's my log file. Hope this helps!

**Comment by ColaniYT** [comment]
I’ve looked through the files of the project and found that there is no discord_games_sdk file for arm devices (only x86).

Could it be that everyone having this issue is running minecraft on an arm device and that that is an issue?

I’ll have a look later if I can find an arm compatible file and if I can manage to swap the files. Maybe that solves the issue.

I’ll edit this comment with the outcome once I got around to do it.

Alternatively, what files would I need to edit to remove the discord presence?

**Comment by AsoDesu** [comment]
The library i use for Discord GameSDK does not yet support ARM devices
I am looking into switching to one that is a little more up-to-date

I've realised that IslandUtils tries to create Discord Presence regardless of whether the option is disabled or not,
I'll push an update later to not bother with the Discord SDK if it's disabled, or if the SDK is not found.

**Comment by eklyst** [comment]
has this feature been implemented yet?

> The library i use for Discord GameSDK does not yet support ARM devices I am looking into switching to one that is a little more up-to-date
> 
> I've realised that IslandUtils tries to create Discord Presence regardless of whether the option is disabled or not, I'll push an update later to not bother with the Discord SDK if it's disabled, or if the SDK is not found.
