### ISSUE TITLE
Option to disable config button in options menu

### ISSUE THREAD

**Issue by MicrocontrollersDev** [AsoDesu/IslandUtils#39]
Just a preference thing. I use Mod Menu and I don't like the look of the extra button in the corner.

**Comment by AsoDesu** [comment]
Can do 👍

**Comment by xttlegendgithub** [comment]
Please do this! Thank you!

**Comment by Karkkikuppi** [comment]
Implemented in https://github.com/AsoDesu/IslandUtils/commit/e12f3b20fc6ca9c38c953c8c11913e2370476490
