### ISSUE TITLE
Can't get the event music to play in game on the latest version

### ISSUE THREAD

**Issue by Ventinthesky** [AsoDesu/IslandUtils#43]
i recently just updated from 1.19.3 to 1.19.4 on fabric, when i hop on the mini games on server the music didn't come on. So at first i thought i have broken something by changing some of the settings, i have redownloaded both fabric, and islandutils a couple time to no avail. i have tested this on a fully fresh installation of minecraft with just fabric api and utils to be yielded the same result. I only encounter this issue on 1.19.4 specifically, 1.19.3 and 1.19.2 are working just fine.

**Comment by Ventinthesky** [comment]
[latest.log](https://github.com/AsoDesu/IslandUtils/files/11062151/latest.log)

This is tested on a fresh install of 1.19.4 fabric with islandutils and fabric api. 
I have properly checked that my music slider is on.

i have debug mode on but don't know what that do

**Comment by AsoDesu** [comment]
Did you have debug mode on for this log?

**Comment by AsoDesu** [comment]
I just realised,
You're joining through `mccisland.com` instead of `mccisland.net`
Could you try joining through `mccisland.net` instead?

**Comment by Ventinthesky** [comment]
ah so that was my problem, i swap the ip and it working fine. Big thanks Aso! <3

**Comment by AsoDesu** [comment]
I do recognise this as a genuine issue tho, so i'll keep this open for now until i fix it
