### ISSUE TITLE
When present, IslandUtils removes the `Mod` button from ModMenu in the escape menu

### ISSUE THREAD

**Issue by Kaizodude** [AsoDesu/IslandUtils#45]
Issue is as described in the title

With IslandUtils disabled
![image](https://user-images.githubusercontent.com/2174905/228262105-ebd9200a-c827-48ec-810e-68e656e09fa7.png)

With IslandUtils enabled
![image](https://user-images.githubusercontent.com/2174905/228262427-905a25b5-979f-4fdd-b5ac-d7bc7ea1b97c.png)

This occurs on Minecraft 1.19.4 with Fabric API 0.76.0

**Comment by kispintyi** [comment]
Same issue!

**Comment by AsoDesu** [comment]
Fixed in [Hotfix 1.3.2](https://modrinth.com/mod/island-utils/version/1.3.2)
Thank you!
