### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by S4MON1X** [AsoDesu/IslandUtils#49]
I have swapped version to 1.20.1 for playing on SMP and I also want to play on MCCI. Is it possible to release mod for that version?

**Comment by AsoDesu** [comment]
Will do soon when i get a moment 👍

**Comment by S4MON1X** [comment]
> Will do soon when i get a moment 👍

Ok, ty

**Comment by AsoDesu** [comment]
Updated in 1.4.1
