### ISSUE TITLE
Suggestion: Cosmetic Previews

### ISSUE THREAD

**Issue by FayneAldan** [AsoDesu/IslandUtils#5]
It would be nice if we could have a preview of cosmetics in the wardrobe, shops, and barber; similar to how Bedrock Edition and the Essential mod shows your character on the side of the screen.
![image](https://user-images.githubusercontent.com/1149870/187139037-5b1e8278-75be-4ed0-897b-a45a74800221.png)
![image](https://user-images.githubusercontent.com/1149870/187138986-d3d08114-b4cb-4757-a6fd-286297ea0944.png)

**Comment by AsoDesu** [comment]
ooooooo, that would be so nice,
I'll add that to the to-do list :D

**Comment by FayneAldan** [comment]
Only thing is that probably wouldn't be possible to preview trails and auras unless you replicate the server sending particles (I assume). For hats and accessories, you can probably just detect what item is selected in the current HUD (or the item you're being prompted to purchase), detect if it's a hat or accessory, then render the player with the item in the appropriate slot (helmet or off-hand).

**Comment by AsoDesu** [comment]
yep :P

**Comment by AsoDesu** [comment]
Added 1.1.0
