### ISSUE TITLE
pkw music stops at 6 minutes

### ISSUE THREAD

**Issue by AGoodGuyMe** [AsoDesu/IslandUtils#54]
the parkour warrior music is stopping at 6 minutes into the course

**Comment by thedoctor1645** [comment]
I just tested this twice and it doesn't stop at 6 minutes (played once for over 48 minutes)

**Comment by AsoDesu** [comment]
is this still an issue?

**Comment by AGoodGuyMe** [comment]
ok this is weird, it SOMETIMES stops at 2 minutes, not 6 minutes anymore, but not when im afk only when im actually doing the course

**Comment by AsoDesu** [comment]
This *should* be fixed in: https://github.com/AsoDesu/IslandUtils/commit/f3768b4d7b134c0d1f962851bf45a86d1ecdb230
