### ISSUE TITLE
Music loop PKW

### ISSUE THREAD

**Issue by thedoctor1645** [AsoDesu/IslandUtils#55]
If you restart a course and finish a course just as the music is about to start the loop again it'll continue playing

**Comment by thedoctor1645** [comment]
![2023-06-25_20 45 34](https://github.com/AsoDesu/IslandUtils/assets/113479465/e400436e-0df7-42cc-9e9a-0bbbab2014be)
This being an example. And yes the music stops after another 2 minutes (if you are still in the course you finished in) but I thought it should be mentioned

**Comment by AsoDesu** [comment]
Fixed in: https://github.com/AsoDesu/IslandUtils/commit/f3768b4d7b134c0d1f962851bf45a86d1ecdb230
