### ISSUE TITLE
Spacewall not looping

### ISSUE THREAD

**Issue by FruitcakeLIVE** [AsoDesu/IslandUtils#56]
**Describe the bug**
The music of hole in the wall "superwall" does not loop and stops near the end

**To Reproduce**
Steps to reproduce the behaviour:
1. turn on classic music for HITW
2. play a game of hole in the wall
3. last until the end of the game

**Expected behaviour**
a clean loop of the music until overtime kicks in

**Screenshots & Logs**
If applicable, add screenshots or log snippets to help explain your problem.

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: 17
- Minecraft Version: 1.19.4
- IslandUtils Version: 1.4.2
- OS: Windows
- CPU: see screenshot
![cpu](https://github.com/AsoDesu/IslandUtils/assets/109293455/c97dfefb-0b35-4567-8e1d-70ada5b20c6e)

**Additional context**

**Comment by AsoDesu** [comment]
Should be fixed in: https://github.com/AsoDesu/IslandUtils/commit/f3768b4d7b134c0d1f962851bf45a86d1ecdb230
