### ISSUE TITLE
Cosmetic preview changes

### ISSUE THREAD

**Issue by LiamDun** [AsoDesu/IslandUtils#57]
can a setting please be added to bring back how the cosmetic previews used to work, really not a fan of having to press a key every single time I want to preview a cosmetic rather then how it used to be where I could just hover over it and see the preview.

**Comment by AsoDesu** [comment]
I can add a toggle for it
I originally removed them because they were difficult to maintain & had a lot of issues
Most of these issues are gone now so they can probably return :D

**Comment by AsoDesu** [comment]
Added in 1.4.3 :D
