### ISSUE TITLE
Parkour Warrior Survivor Updates

### ISSUE THREAD

**Issue by AsoDesu** [AsoDesu/IslandUtils#58]
**Parkour Warrior: Survivor has been released, this issue tracks the progress on getting IslandUtils fully updated!**

- [x] Change how PKW is detected
  - [x] Use tablist to detect Hub
  - [x] Use tablist to detect Dojo
  - [x] Use tablist to detect Survivor
- [x] Send proper presence for survivor
- [x] Fix music jankyness
  - [ ] Fade must & un-fade music ?

**Comment by 1unar-Eclipse** [comment]
Imo music would work better if it kept going from start to finish regardless of completing leaps

**Comment by JOOT49** [comment]
Music also never stops at the end of a match it just keeps going

**Comment by AsoDesu** [comment]
> Imo music would work better if it kept going from start to finish regardless of completing leaps

that was kinda that the music wouldn't stop or restart at all, however i still want the overtime music to play when you're running out of time, so my idea was to fade out the music when overtime plays, and then un-fade once it stops, if that makes sense?
