### ISSUE TITLE
Improve on Chat Notifications

### ISSUE THREAD

**Issue by Zekcya** [AsoDesu/IslandUtils#59]
So things like, you complete a quest, unlock a new reward in the battle pass or game pass, or unlock a badge. All those things that appear in the chat. It would be nice if there was a more clear notification when these things happen so it doesn't get buried in chat and you forget about them. It could just be that I am blind and very forgetful but this would be a nice feature.

**Comment by AsoDesu** [comment]
That could be nice

**Comment by kispintyi** [comment]
@AsoDesu @Zekcya Its already a thing in an other mod

**Comment by Zekcya** [comment]
I looked into it and it seems that the mod uses toasts (kinda like the advancement thingy) to notify the player. Though those disappear after a short time. What could be interesting is to have something similar to "Pick Up Notifier" by Fuzs where it's like a second "chat" on the right side of the screen for only those notifications. Additionally, depending on the complexity could be persistent until claimed or acknowledged.

**Comment by RobinRMC** [comment]
> @AsoDesu @Zekcya Its already a thing in an other mod

Yeah, I'm using both Island Utils and [MCCI: Companion](https://modrinth.com/mod/mccic).

It'd be great if the features from [MCCI: Companion](https://modrinth.com/mod/mccic) get implemented in Island Utils, as [MCCI: Companion](https://modrinth.com/mod/mccic) doesn't seem to be maintained anymore and it has some nice features.

**Comment by AsoDesu** [comment]
I'm gonna close this as not planned for now, i think MCCIs notifications are enough for now, i may revisit things for things such as notification toasts at a later date
