### ISSUE TITLE
Tgttos "To The Dome!" map uses a different song

### ISSUE THREAD

**Issue by AGoodGuyMe** [AsoDesu/IslandUtils#60]
In MCC, the Tgttos "To The Dome!" map uses the song "One Minute to MCC!" which would just be a nice little addition to the mod, if it were to have that different song for that map

**Comment by AsoDesu** [comment]
Good idea!

**Comment by AsoDesu** [comment]
Fixed in: https://github.com/AsoDesu/IslandUtils/pull/68
