### ISSUE TITLE
Pkw survivor music keeps playing

### ISSUE THREAD

**Issue by AGoodGuyMe** [AsoDesu/IslandUtils#65]
The Parkour Warrior Survivor music continues to play once the game has finished, if you are still alive, and no one completes the second to last leap, then the game ends after the timer and the music is still playing

**Comment by MrKacafirekCZ** [comment]
This issue seems to also happen when you finish 1st in the final leap.

**Comment by AsoDesu** [comment]
Fixed in: https://github.com/AsoDesu/IslandUtils/commit/084eb5fecb69c5e8002f0219b4ec4ecc1fbe085a
