### ISSUE TITLE
Server shifts the bossbar, breaking the timer bar

### ISSUE THREAD

**Issue by Hyphrio** [AsoDesu/IslandUtils#77]
**Describe the bug**
Server may sometimes shift the bossbar a bit lower, which causes conflict with the new feature.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Parkour Warrior: Dojo, select any course.
2. Click Mode Swap (Practice Mode)
3. Click Mode Swap again (Challenge Mode)
4. Start a round
5. See error

**Expected behaviour**
The splits timer would maybe adjust? (not sure)

**Screenshots & Logs**
![1](https://github.com/AsoDesu/IslandUtils/assets/79437385/52ec7368-c802-4841-97f9-cb8215c3cce2)
![2](https://github.com/AsoDesu/IslandUtils/assets/79437385/522f17cd-4164-474c-8cf7-9437232923fb)
![3](https://github.com/AsoDesu/IslandUtils/assets/79437385/ef98b416-ae9c-4e83-b4ec-cdd1b0fdf3da)
![4](https://github.com/AsoDesu/IslandUtils/assets/79437385/b88509cc-0e11-4b35-96fd-af9717efe1ee)

**System & Version Information**
 - Java Version: 17
- Minecraft Version: 1.20.1
- IslandUtils Version: v1.5.0-pre2-pre+76-main (beta, artifacts from Actions)
- OS: Windows
- CPU: i5-7200U

**Additional context**
This could also be a bug within MCCi / Minecraft, I think it might be a good idea to detect when the bossbar has shifted, or detect when practice mode was clicked to work around this. It is probably better to report this a bit earlier.

**Comment by AsoDesu** [comment]
Fixed in: https://github.com/AsoDesu/IslandUtils/commit/cb8b910d54991939e9ed7d037b85c32b7c669c82
