### ISSUE TITLE
2 times music

### ISSUE THREAD

**Issue by Remko115** [AsoDesu/IslandUtils#8]
When playing another game the music from the last game keeps playing

**Comment by AsoDesu** [comment]
Are you using any mods along with IslandUtils?

**Comment by Remko115** [comment]
yea these mods

	- reeses-sodium-options 1.4.7+mc1.19.2-build.59
	- servercore 1.3.1-1.19.1
	- smoothboot 1.19-1.7.1
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.9+mc1.19.2-build.60
	- starlight 1.1.1+fabric.ae22326
	- toomanyplayers 1.19-1.1.4
	- tweakeroo 0.14.3
	- viabackwards 4.4.1
	- viafabric 0.4.8+16-main
	- viafabric-mc119 0.4.8+16-main via viafabric
	- viarewind 2.0.2
	- viaversion 4.4.2-SNAPSHOT via viafabric
	- vmp 0.2.0+beta.6.56
	- waveycapes 1.2.1
	-  c2me 0.2.0+alpha.8.2
	- - caffeineconfig 1.0.0+1.17 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.0.75 via islandutils
	- - cullleaves 2.3.4
	- custom-crosshair-mod 1.5.0-fabric
	- dashloader 4.0.0+1.19
	- debugify 2.5.0
	- dev_quantumfusion_hyphen 0.2.2 via dashloader
	- dev_quantumfusion_taski 1.1.0 via dashloader
	- eatinganimationid 1.9
	- entityculling 1.5.2-mc1.19
	- fabric 0.58.6+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via sodium
	- - feather 1.0.0-SNAPSHOT
	- ferritecore 4.2.1
	- hideplayers 1.19.2-1.3
	- iris 1.2.8
	- islandutils 1.0.0
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- krypton 0.2.1
	- ksyxis 1.1
	- lazydfu 0.1.3
	- libgui 6.0.0+1.19 via toomanyplayers
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.3
	- malilib 0.13.0
	- mcciutils 0.6
	- me_lucko_spark-api 0.1-SNAPSHOT via servercore
	- memoryleakfix 1.19.1-0.7.0
	- midnightlib 0.5.2
	- minecraft 1.19.2
	- minecraftcapes 12.1.0
	- modmenu 4.0.6
	- moreculling 1.19.1-0.10.0

**Comment by LukynkaCZE** [comment]
Fixed this in [hotfix release 1.1.1](https://github.com/AsoDesu/IslandUtils/releases/tag/1.1.1)
