### ISSUE TITLE
Mod doesn't work on Prism launcher?

### ISSUE THREAD

**Issue by WilliamPlays0402** [AsoDesu/IslandUtils#80]
**Describe the bug**
The mod doesn't work on any configurations of prism launcher.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Prism launcher
2. Create a new instance
3. Install the mod and its dependencies

**Expected behaviour**
Mod works.

**Screenshots & Logs**
If applicable, add screenshots or log snippets to help explain your problem.

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: 17.0.1
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.5.0
- OS: Windows 11
- CPU: Intel i7-10750H

**Additional context**
The mod works on the regular Minecraft launcher.

**Comment by WilliamPlays0402** [comment]
Thanks for the swift reply!
I've also tried your competitor: MCC: Island Companion, and that doesn't work either.
Here is the log: https://mclo.gs/wTuxjId

**Comment by WilliamPlays0402** [comment]
And here is a screenshot of the "preview collectables" feature not working:
![image](https://github.com/AsoDesu/IslandUtils/assets/49759911/c44bc1a6-b6e3-421f-8392-f88b42d89e0b)

**Comment by AsoDesu** [comment]
If you are connecting through an `mccisland.com` IP
Please try connecting through `play.mccisland.net` instead

**Comment by WilliamPlays0402** [comment]
> If you are connecting through an `mccisland.com` IP Please try connecting through `play.mccisland.net` instead

I am already connecting through `play.mccisland.com`.

**Comment by AsoDesu** [comment]
yes, please try connecting through `play.mccisland.net`

**Comment by WilliamPlays0402** [comment]
> yes, please try connecting through `play.mccisland.net`

I've tried that already, as per the screenshot attached before.
Should I try something else?

**Comment by AsoDesu** [comment]
> I've tried that already, as per the screenshot attached before. Should I try something else?

The screenshot you attached shows the IP as `play.mccisland.com`.
I've recognised that a lot of people connect through `.com` and so that will be fixed in the next update.

However, i just want to be sure there aren't any more issues, so please can you try connecting to
`play.mccisland.net` (thats with a `.net` *not* a `.com`)

**Comment by WilliamPlays0402** [comment]
Thank you very much, it was the ip address!
Could you put this into the description of the mod (or into something else), or could you add the other ip addresses aswell, so that other people do not have the same issue?
Thanks again for the swift replies and for your assistance!

**Comment by AsoDesu** [comment]
I've commited a fix (https://github.com/AsoDesu/IslandUtils/commit/2d3544b90a972df0e3f3db3ef4e2bc2f9d6be993) and this will be fixed in the next update :D
Thank you
