### ISSUE TITLE
Minecraft not launching

### ISSUE THREAD

**Issue by thedoctor1645** [AsoDesu/IslandUtils#82]
I tried to open Minecraft with the latest version of the mod.

I open the launcher click play and shortly after the game crashes, it doesn't even show me the Mojang Studios loading screen.

Obviously the expected behaviour is for the game to load normally

[crash-2023-08-11_22.18.22-client.txt](https://github.com/AsoDesu/IslandUtils/files/12324452/crash-2023-08-11_22.18.22-client.txt)

 - Java Version: Java 17.0.3
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.5.1
- OS: Windows 11
- CPU: Intel i7--8565U

**Comment by AsoDesu** [comment]
You need the 1.0 release of Noxesium
https://modrinth.com/mod/noxesium/version/1.0.1
