### ISSUE TITLE
PKW Dojo time splits does not disappear even after disabling it

### ISSUE THREAD

**Issue by Gameoholic** [AsoDesu/IslandUtils#86]
**Describe the bug**
If you disable the PKW Dojo time splits mid-run, the timer bar will not go away, will continue counting (even if you restarted/ended the run), and will not disappear until you leave and join back the lobby.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a PKW Dojo run with the option "Enable PKW: Dojo time splits" enabled.
2. Disable the "Enable PKW: Dojo time splits" option mid-run.
3. Restart/finish the course. The timer will continue counting.

**Expected behaviour**
I expected the timer to disappear immediately after disabling the option. If this isn't intended behaviour, then for the timer to at least disappear upon finishing/resetting the run.

**System & Version Information**
(This can usually be found in the F3 Menu)
 - Java Version: Java 17
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.5.1
- OS: Windows

**Comment by Gameoholic** [comment]
I've made a simple fix for this, where upon ending/restarting the run, it sets the leveltimer instance to null if the EnablePkwSplits option is disabled.
However, the timer doesn't disappear immediately upon changing the setting if you're mid-run, and I'm not sure if you want it to do that.

**Comment by AsoDesu** [comment]
Fixed in 1.6.0
