### ISSUE TITLE
Add ability to disable teleport transitions

### ISSUE THREAD

**Issue by pe3ep** [AsoDesu/IslandUtils#87]
Every time you leave/join the game, it makes a transition (_black screen fading in and out_). It's achieved by sending a title with a specific character.

The issue is that sometimes the transition can feel too long or obstructive (_for example, when you change courses in PKW: Dojo_).
It would be really nice to have the ability to disable these transitions

**Comment by AsoDesu** [comment]
Teleport transitions are there to hide some weird chunk loading and other things MCCI does in the background while you are teleporting
Because of that I don't really want to add a way to disable them.
