### ISSUE TITLE
Parkour Warrior music starts playing again once you win the game

### ISSUE THREAD

**Issue by MrKacafirekCZ** [AsoDesu/IslandUtils#88]
**Describe the bug**
Parkour Warrior music starts playing again once you finish all 8 leaps and win the game.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get into a game of Parkour Warrior Survivor.
2. Finish all 8 leaps and win the game.
3. You will be able to hear both the game win music and Parkour Warrior music playing at the same time.

**Expected behaviour**
Parkour Warrior music should not play at this moment as it overlaps with a game win music.

**Screenshots & Logs**
N/A

**System & Version Information**
 - Java Version: 17
- Minecraft Version: 1.20.1
- IslandUtils Version: 1.5.0
- OS: Windows
- CPU: AMD Ryzen 5

**Additional context**
N/A

**Comment by AsoDesu** [comment]
This is difficult for me to test because i am not very good at PKW: Survivor :)
This issue has come up a lot and i have an idea for a possible solution, i just need to make sure it doesn't break anything else

**Comment by AsoDesu** [comment]
Should be fixed in 1.6.0
