### ISSUE TITLE
Parkour Warrior Music fade in when finishing leap in the exact same time as the music starts fading out

### ISSUE THREAD

**Issue by MrKacafirekCZ** [AsoDesu/IslandUtils#89]
**Is your feature request related to a problem? Please describe.**
I often find myself finishing a leap around the time when it says "Next leap in 00:14" or "Next leap in 00:15". At this exact time the music starts fading out. When I finish the music starts over and playing at the player's specified volume.

**Describe the solution you'd like**
It would be nice to have the music fade in while it's still playing. If it's no longer playing (aka the overtime music is playing), the currently implemented solution works well enough (aka overtime music stops and Parkour Warrior music starts playing again from the beginning).

**Describe alternatives you've considered**
No alternatives have been considered.

**Additional context**
N/A

**Comment by AsoDesu** [comment]
This is something that i originally wanted to do with the survivor music, but i ran into a lot of issues and kinda just wanted to get it out lmao
I'll have a look and see what i can do

**Comment by MrKacafirekCZ** [comment]
Yeah I actually tried to do this myself but I ran into an annoying Minecraft "feature" (I guess) and that's any sound with volume 0 is immediately getting stopped.

**Comment by AsoDesu** [comment]
yeaa that's given me way too many issues lmao

**Comment by MrKacafirekCZ** [comment]
Hm I just had an idea, if it's possible to set the volume to such a value that you can't hear anything as the player but it's still not equal 0 meaning Minecraft will not stop that sound.

**Comment by AsoDesu** [comment]
thats how Noxesium stops the music from stopping when you set a volume slider to 0
