### ISSUE TITLE
The character preview is open in all menus

### ISSUE THREAD

**Issue by Ludus56** [AsoDesu/IslandUtils#9]
The preview of your character is open in all menu's, including ones not related to cosmetics.
![2022-09-12_18 52 32](https://user-images.githubusercontent.com/89146605/189772169-235a0493-f9d9-44d9-bf11-74e271d1c51e.png)
![2022-09-12_18 58 10](https://user-images.githubusercontent.com/89146605/189772716-44d591d5-f13d-4e88-90e6-a3b747bb5f15.png)
![2022-09-12_18 57 57](https://user-images.githubusercontent.com/89146605/189772727-8a1e659e-a82a-4db5-b4a4-5684e5d277f4.png)
![2022-09-12_18 58 00](https://user-images.githubusercontent.com/89146605/189772728-a6ab2c1d-0454-4b18-9134-ecfa38c752f7.png)
![2022-09-12_18 58 03](https://user-images.githubusercontent.com/89146605/189772731-5c1a1f4a-72d6-48e9-bf1f-ead8e3510aea.png)

**Comment by FayneAldan** [comment]
Maybe there could be a setting to only show the preview if the preview is updated (from hovering over items)

**Comment by LukynkaCZE** [comment]
Yeah the menu is supposed to be opened in pretty much all menus. Only issue with that is the beta warning screen in #12
Can probably add setting to hide it in non-cosmetic menus tho

**Comment by LukynkaCZE** [comment]
Add this in [hotfix release 1.1.1](https://github.com/AsoDesu/IslandUtils/releases/tag/1.1.1)
