### ISSUE TITLE
Item lore says middle click to preview cosmetic no matter what it's actually bound to

### ISSUE THREAD

**Issue by LiamDun** [AsoDesu/IslandUtils#90]
![image](https://github.com/AsoDesu/IslandUtils/assets/62409548/4e9cbd8f-ce8d-4963-94fd-73fdcdb09555)
no idea if this is intentional but "Middle Button to Preview on player" (no idea why preview and button are capitalized btw) always stays in the item lore of cosmetics even if it's set to any key other then middle click / not bound to anything, it would be nice to have an option to get rid of this text without having to fully disable cosmetic previews (as I currently have mine set to only show up on hover)

**Comment by AsoDesu** [comment]
The binding is the one that is bound to *Pick Block*, the "Preview Cosmetic" keybind is no longer used and i forgot to remove it
I will work on fixing this, probably tomorrow 

also the name of it ("Middle Button") is provided by Minecraft so thats what the weird capitalisation is
