### ISSUE TITLE
Add ability to view quests in games

### ISSUE THREAD

**Issue by pe3ep** [AsoDesu/IslandUtils#91]
Having ability to view current quests/quest scrolls during games would be really useful

**Comment by AsoDesu** [comment]
This is possible but since there is no way for me to get quests without storing them, it could have a few issues with them being de-synced if they were changed, and there isn't a way for me to update if they're completed.

This is a feature i'd be interested in taking a look at in the future!

**Comment by pe3ep** [comment]
I don't like to necropost, but I want to say that this feature is awesome and I really want it to be added in here.

**Comment by AsoDesu** [comment]
I'm gonna close this for now, i have no real way of getting information about quests reliably
I may revisit this in the future if we're given access to quests with the MCCI API
