### ISSUE TITLE
Chat Toggle

### ISSUE THREAD

**Issue by LobbyLC** [AsoDesu/IslandUtils#93]
I noticed a player was trying to disable chat earlier (hiding all player messages while keeping important server messages) and, since I've seen multiple ask if this is possible, I thought I'd suggest it to you!

I believe the way this would work is you'd have three options.
1. See all chat messages *(default)*
2. Only see chat messages sent by friends, party, team and the server
3. Only see chat messages sent by the server

![image](https://github.com/AsoDesu/IslandUtils/assets/116382138/1d2918ac-befa-4b1c-b40c-daad356d5f6a)

To disable chat entirely, the vanilla method still works, but that's not a great option as it hides important messages (such as game updates) so I feel as though this would be a fitting feature for Island Utils!

**Comment by AsoDesu** [comment]
This has been a feature i've wanted to add but i was unsure on if it would be used/wanted lol

**Comment by lucyydotp** [comment]
Hi, hope you don't mind me poking my head in here. We're fixing the vanilla chat visibility system in an upcoming Island update, so "commands only" will still show game/system messages but hide player chat.
