### ISSUE TITLE
update to 1.20.2

### ISSUE THREAD

**Issue by BluSpring** [AsoDesu/IslandUtils#97]
just gonna leave this as a reminder/note for you :)

**Comment by AsoDesu** [comment]
Waiting for Noxesium to update :P

**Comment by BluSpring** [comment]
update time :D

**Comment by AsoDesu** [comment]
All current features have been updated to 1.20.2
I will test further and release the update once Noxesium has officially released the 1.20.2 update

**Comment by RuiNtD** [comment]
> All current features have been updated to 1.20.2 I will test further and release the update once Noxesium has officially released the 1.20.2 update

Noxesium was updated on Modrinth literally the day you posted this btw. lol

**Comment by AsoDesu** [comment]
Updated in 1.6.2 - 1.20.2
