### ISSUE TITLE
Dynamite dogeball music doesnt start at correct time

### ISSUE THREAD

**Issue by LukynkaCZE** [AsoDesu/IslandUtils#99]
**Describe the bug**
Dynaball music starts way later in the song than it should

**To Reproduce**
1. Play dynaball

**Expected behaviour**
Music should start at 0, from the beggning

**Comment by AsoDesu** [comment]
This is semi intended behaviour because the music needs to loop and so i had to chop off a ltitle on the start, and i don't really have a way to start it at 0 for the first loop

**Comment by NotJacobGGG** [comment]
Just deal with it
